name: DeployDocsToGHPages
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.6
      - name: install
        run: poetry install -E docs
      - name: Build
        run: |
          mkdir gh-pages
          cd docs/
          poetry run sphinx-apidoc -o source/ ../spb_curate
          poetry run sphinx-build -d ./_build.doctrees -b html . _build
          cp -r _build/* ../gh-pages/
          cp _build/.nojekyll ../gh-pages/
      - name: Deploy GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: true
          branch: gh-pages
          folder: gh-pages
